name: pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
  
jobs:
  pytest:
    name: Run test with pytest
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # pytestをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # pytest -> JUnit xml形式で結果を出力
      - name: PyTest
        run: |
          python -m pytest tests --junit-xml results/pytest.xml
        continue-on-error: true